framework:
    secret: '%env(APP_SECRET)%'
    test: true
    session:
        storage_factory_id: session.storage.factory.mock_file
    http_method_override: false
    handle_all_throwables: true

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
